# Change these first
owner: jacksonkocon # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Torra+
    url: 
  - name: Request
    url: 
  - name: Account
    url: 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.torraplus.com
  # baseUrl: uptime
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Torra+ Server Status
  introTitle: "**Uptime"
  introMessage: 
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
